# Generated by Django 4.1.6 on 2023-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.IntegerField(default=0, verbose_name='имя')),
                ('books', models.CharField(max_length=50, verbose_name='Книги')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('category_id', models.IntegerField(default=0, verbose_name='Категории ID')),
                ('author_id', models.IntegerField(default=0, verbose_name='Автор книг')),
                ('tags', models.ManyToManyField(to='task.tag', verbose_name='Теги')),
            ],
        ),
    ]
